# Generated by Django 4.2.1 on 2023-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('state', models.CharField(max_length=50, verbose_name='Штат')),
                ('postal_code', models.IntegerField(unique=True, verbose_name='Почтовый индекс')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
